config/routes.rb
Rails.application.routes.draw do
  delete '/logout', as: :logout, to: 'sessions#destroy'
  root 'landing#show'
  get '/home', to: 'home#show'
  get '/auth/twitter/callback', to: 'sessions#create'
  get '/auth/twitter', as: :login
  resources :users
  resources :parties
  resources :songs
  resources :party_songs

  namespace :api do
    namespace :v1 do
      post 'add_song', to: 'search#add_song'
      delete 'remove_song', to: 'search#remove_song'
    end
  end
end

app/models/party.rb
class Party < ActiveRecord::Base
  belongs_to :user
  has_many :party_songs
  has_many :songs, through: :party_songs

  validates :name, presence: true, uniqueness: true
  validates :slug, presence: true

  extend FriendlyId
  friendly_id :name, use: :slugged

end

app/models/party_song.rb
class PartySong < ActiveRecord::Base
  belongs_to :party
  belongs_to :song
end

app/models/song.rb
class Song < ActiveRecord::Base
  has_many :party_songs
  has_many :parties, through: :party_songs
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :parties

  validates :name, uniqueness: true;

  def self.from_omniauth(auth_info)
    if user = find_by(uid: auth_info.uid)
      user
    else
      create({name: auth_info.extra.raw_info.name,
              screen_name: auth_info.extra.raw_info.screen_name,
              uid: auth_info.uid,
              oauth_token: auth_info.credentials.token,
              oauth_token_secret: auth_info.credentials.secret
             })
    end
  end

end

app/controllers/api/v1/search_controller.rb
class Api::V1::SearchController < ApplicationController
  require 'uri'

  def add_song
    song_url = params[:song][:permalink_url]
    party_path = params[:song][:party_path]
    uri = URI(party_path)
    party_slug = uri.path.split("/")[-1]
    # song = Song.create(url: song_url)
    song = Song.create(url: song_url) if Song.find_by(url: song_url).nil?
    party = Party.friendly.find(party_slug)
    party.party_songs.create(song: song)
    byebug
    respond_to do |format|
      format.js { render json: {success: true} }
      format.json { render json: {success: true} }
    end
  end

  def remove_song
    song_index = params[:song][:song_index].to_i
    party_path = params[:song][:party_path]
    uri = URI(party_path)
    party_slug = uri.path.split("/")[-1]
    party = Party.friendly.find(party_slug)

    songs_group = []

    party.songs.each do |song|
      songs_group << song
    end

    song_to_remove = songs_group[song_index]
    party.party_songs.find_by(song_id: song_to_remove.id).destroy

    respond_to do |format|
      format.js { render json: {success: true} }
      format.json { render json: {success: true} }
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
    @party = Party.new
  end
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def show
  end
end

app/controllers/parties_controller.rb
class PartiesController < ApplicationController
  before_action :set_party, only: [:show]

  def show
  end

  def create
    @party = Party.new(party_params)
    @party.user_id = current_user.id
    if @party.save
      redirect_to party_path(@party)
    else
      redirect_to home_path
    end
  end

  private

  def party_params
    params.require(:party).permit(:name)
  end

  def set_party
    @party = Party.friendly.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @user = User.from_omniauth(request.env["omniauth.auth"])
    if @user
      session[:user_id] = @user.id
      redirect_to home_path
    else
      redirect_to root_path
    end
  end

  def destroy
    session.clear
    redirect_to root_path
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/parties_helper.rb
module PartiesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/home/show.html.erb
<div class="container">

  <div class="row">
    <% if current_user.parties.empty? %>
        <div class="col-lg-6 col-lg-offset-3">
          <div id="welcome-banner">
            <h1>Start a Party!</h1>
            <%= render 'shared/party_form' %>
          </div>
        </div>
    <% else %>
        <div class="col-lg-4 col-lg-offset-2">
          <h1>Start a Party!</h1>
          <%= render 'shared/party_form' %>
        </div>

        <div class="col-lg-4 col-lg-offset-1">
          <h1>Your Past Parties</h1>
        <%= render 'shared/party_list' %>
    <% end %>
    </div>
  </div>
</div>

app/views/landing/show.html.erb
<div id="home-banner">
  <h1>A Social Playlist For <span class="element"></span></h1>
  <hr>
  <%= link_to "Login With Twitter", login_path, class:"btn btn-lg btn-info btn-ghost" %>
</div>

<%= render partial: 'shared/landing' %>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= render 'shared/logo' %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <%= render 'shared/login_logout' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Collaborave - A Social Playlist for Parties</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href='http://fonts.googleapis.com/css?family=Nunito' rel='stylesheet' type='text/css'>
  <script src="//connect.soundcloud.com/sdk-2.0.0.js"></script>
  <script>
  SC.initialize({
    client_id: '<%= ENV['SC_CLIENT_ID'] %>',
    redirect_uri: 'http://collaborave.herokuapp.com/callback'
  });
  </script>
  <%= csrf_meta_tags %>
</head>

<body>
  <%= render partial: 'layouts/nav' unless current_page?(root_url) %>

  <%= yield %>

</body>
</html>

app/views/layouts/landing.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Collaborave - A Social Playlist for Parties</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href='http://fonts.googleapis.com/css?family=Nunito' rel='stylesheet' type='text/css'>
  <script src="//connect.soundcloud.com/sdk-2.0.0.js"></script>
  <script>
  SC.initialize({
  client_id: '<%= ENV['SC_CLIENT_ID'] %>',
  redirect_uri: "http://collaborave.herokuapp.com/callback"
});

  </script>
  <%= csrf_meta_tags %>
</head>
<body id="background">
<%= render partial: 'layouts/nav' unless current_page?(root_url) %>

<%= yield %>

</body>
</html>

app/views/parties/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-3 col-lg-offset-1">
      <div id="party-sidebar">
        <h1><%= @party.name %></h1>
        <%= render 'shared/click_to_tweet' %>
        <hr>
      </div>
      <div class="input-group">
        <input id="search" type="search" name="search" type="text" class="form-control" placeholder="Add Songs via SoundCloud">
      <span class="input-group-btn">
        <button class="btn btn-default btn-search" type="button">Go!</button>
      </span>
      </div>
      <div id="sc-results"></div>
    </div>

    <div class="col-lg-6 col-lg-offset-1">
      <div id="player" class="sc-player">
      </div>
    </div>
  </div>
</div>
<%= render 'shared/player' %>

app/views/shared/_click_to_tweet.html.erb
<h3><a class="btn btn-lg btn-info"
       href="https://twitter.com/intent/tweet?text=Come%20%26%20Party%20with%20me%20on%20%40Collaborave!%20Add%20songs%20to%20my%20playlist%20here%3A%20&url=http%3A%2F%2Fcollaborave.herokuapp.com/parties/<%= @party.slug %>&via=NYDrewReynolds"
       data-size="large" data-count="none"><i class="fa fa-twitter"></i> Share Your Party Link</a></h3>

app/views/shared/_landing.html.erb
<style>
    #background {
        background: linear-gradient(
                rgba(220, 20, 60, 0.75),
                rgba(220, 20, 60, 0.75)
        ),
        url('http://guestofaguest.com/wp-content/uploads/2009/05/img_1461.jpg') no-repeat 50% 50% fixed;
        background-size: cover;
        -moz-background-size: cover;
        -o-background-size: cover;
        -webkit-background-size: cover;
    }

</style>

app/views/shared/_login_logout.html.erb
<% if current_user %>
    <li><b><%= current_user.name %></b></li>
    <li><%= link_to "Logout", logout_path, method: :delete %></li>
<% else %>
    <li><%= link_to "Sign In/Sign Up", login_path %></li>
<% end %>

app/views/shared/_logo.html.erb
<% if current_user %>
    <%= link_to "Collaborave", home_path, class: "navbar-brand" %>
<% else %>
    <%= link_to "Collaborave", root_path, class: "navbar-brand" %>
<% end %>

app/views/shared/_party_form.html.erb
<%= form_for(@party, url: {:action => "create", :controller => "parties"}, html: {multipart: true}) do |f| %>
    <%= f.text_field :name, placeholder: 'Name Your Party' %><br>

    <%= f.submit "Get the Party Started!", class: 'btn btn-success' %>
<% end %>

app/views/shared/_party_list.html.erb
<ul>
  <% current_user.parties.each do |party| %>
      <li>
        <%= link_to party.name, party_path(party) %>
        <% if party.songs.count == 1  %>
        - <%= party.songs.count %> Song
            <% else  %>
        - <%= party.songs.count %> Songs
            <% end  %>
      </li>
  <% end %>
</ul>

app/views/shared/_player.html.erb
<script>
    ToneDenReady = window.ToneDenReady || [];
    ToneDenReady.push(function () {
        ToneDen.player.create({
            dom: "#player",
            skin: "light",
            tracksPerArtist: 4,
            shrink: false,
            visualizerType: 'bars',
            urls: [
                <% @party.songs.each do |song | %>
                "<%= song.url %>",
                <% end %>
            ],

            onTrackReady: removeSong
        });
    });
</script>